# Vial configuration
VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
ENCODER_MAP_ENABLE = yes

# Enable features
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
AUTOCORRECT_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Extra features
LAYER_LOCK_ENABLE = yes
TRI_LAYER_ENABLE = yes
